# Generated by Django 5.0.6 on 2024-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waitlists", "0003_waitlistentry_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
